# Generated by Django 4.1.6 on 2023-03-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_teacher_updated_at_alter_teacher_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
