# Generated by Django 4.1.6 on 2023-02-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images'),
        ),
    ]
