# Generated by Django 4.1.6 on 2023-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='techstack',
            field=models.TextField(default='No techstack'),
        ),
    ]
