# Generated by Django 4.1.6 on 2023-02-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_techstack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '3. Students'},
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
