# Generated by Django 4.1.6 on 2023-02-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_options_course_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preferred_track', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('exist_knowledge', models.TextField()),
                ('hours_per_week', models.CharField(max_length=100)),
                ('twitter_link', models.URLField(unique=True)),
                ('why_accept', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interested_category',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(default='No bio'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default='No bio'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
