# Generated by Django 4.1.6 on 2023-02-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mentorship_rename_address_student_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorship',
            options={'verbose_name_plural': '6. Mentorship'},
        ),
        migrations.AddField(
            model_name='mentorship',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='Preferred_track',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='exist_knowledge',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='hours_per_week',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='twitter_link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='why_accept',
            field=models.TextField(null=True),
        ),
    ]
