# Generated by Django 4.1.6 on 2023-03-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_weeklytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_text', models.TextField()),
                ('notif_read_status', models.BooleanField(default=False)),
                ('notif_created_time', models.DateTimeField(auto_now_add=True)),
                ('notif_subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='weeklytask',
            options={'verbose_name_plural': '7. Weeklytasks'},
        ),
        migrations.RemoveField(
            model_name='weeklytask',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='weeklytask',
            name='submitted_file',
        ),
        migrations.AddField(
            model_name='weeklytask',
            name='student_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
