# Generated by Django 4.1.6 on 2023-03-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_notification_alter_weeklytask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '8. Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Notification Created Time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_read_status',
            field=models.BooleanField(default=False, verbose_name='Notification Read Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_subject',
            field=models.CharField(max_length=100, verbose_name='Notification Subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_text',
            field=models.TextField(verbose_name='Notification Text'),
        ),
    ]
