# Generated by Django 4.1.6 on 2023-03-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_notification_notif_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
