# Generated by Django 4.1.6 on 2023-03-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_weeklytask_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='weeklytask',
            name='submission_file',
            field=models.FileField(null=True, upload_to='weeklytask_files'),
        ),
        migrations.AddField(
            model_name='weeklytask',
            name='task_file',
            field=models.FileField(null=True, upload_to='weeklytask_files'),
        ),
    ]
