# Generated by Django 4.1.6 on 2023-03-04 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_weeklytask_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
