# Generated by Django 4.1.6 on 2023-03-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_weeklytask_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
