# Generated by Django 4.1.6 on 2023-03-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_weeklytask_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklytask',
            name='student_status',
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
