# Generated by Django 4.1.6 on 2023-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_weeklytask_student_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_for',
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_text',
            field=models.TextField(null=True, verbose_name='Notification Text'),
        ),
    ]
